apiVersion: v1
kind: Pod
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  hostname: cassandra
  subdomain: monitoring
  containers:
  - name: cassandra
    image: cassandra:3.11
    ports:
    - containerPort: 9042
    env:
    - name: MAX_HEAP_SIZE
      value: 1G
    - name: HEAP_NEWSIZE
      value: 1G
    - name: CASSANDRA_CLUSTER_NAME
      value: thp
    volumeMounts:
    - name: cassandra-data
      mountPath: /var/lib/cassandra/data
  volumes:
  - name: cassandra-data
    emptyDir: {}
